# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171206_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custommer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='period',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='period',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='period', to='shop.Period'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_plan',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='price_plan', to='shop.PricePlan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shop.Custommer'),
        ),
    ]
