# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171206_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custommer_first_name', models.CharField(max_length=50)),
                ('custommer_last_name', models.CharField(max_length=50)),
                ('priceplan', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='shop.PricePlan')),
            ],
        ),
        migrations.AlterField(
            model_name='custommer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custommer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
