# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='code',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
