version: '3'

services:
  db:
    image: mariadb
  shop:
    build: .
    command: python app01/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db